### ISSUE TITLE
HDR to SDR

### ISSUE THREAD

**Issue by buzarini** [7gxycn08/PyAutoActions#3]
Hello! 
Please add the option to reverse switch HDR mode to SDR mode. 
I will be very grateful. Thank you in advance!

**Comment by 7gxycn08** [comment]
Can you give a use case example of what your trying to achieve?

**Comment by buzarini** [comment]
> Can you give a use case example of what your trying to achieve?
I always use HDR in my monitor. I also use [dxvk](https://github.com/doitsujin/dxvk), but vulkan spoils the HDR colors after exiting the game. 
I need to switch the game from HDR to SDR, and after exiting the game, switch back from HDR to SDR.

**Comment by 7gxycn08** [comment]
PyAutoActions automatically switches from HDR to SDR when you quit the game. 
So just to be clear you would like to toggle HDR back on again after exiting the game?

**Comment by buzarini** [comment]
> PyAutoActions automatically switches from HDR to SDR when you quit the game.
> So just to be clear you would like to toggle HDR back on again after exiting the game?

Game startup:
PyAutoActions should switch HDR mode to SDR mode.

Game exit:
PyAutoActions should switch SDR mode to HDR mode.

**Comment by 7gxycn08** [comment]
Requires complete rewrite of program logic.

**Comment by 7gxycn08** [comment]
Here is a test version can you check it out and see if it's working as intended?

Select the mode HDR 2 SDR from the GUI Toggle mode menu and test it out it should disable HDR when the game starts and enable HDR again when the game exits.

SDR 2 HDR mode will enable HDR at game start and disable HDR when the game exits.

![Screenshot 2024-08-19 132016](https://github.com/user-attachments/assets/ac219570-9306-4031-abbb-d0d9591a10fd)



Notice: added a 7z archive to a zip file because github does not support 7z format and max upload size is 25mb
[PyAutoActions.test.zip](https://github.com/user-attachments/files/16658426/PyAutoActions.test.zip)

**Comment by buzarini** [comment]
> Select the mode HDR 2 SDR from the GUI Toggle mode menu and test it out it should disable HDR when the game starts and enable HDR again when the game exits.

HDR 2 SDR mode works great.

> SDR 2 HDR mode will enable HDR at game start and disable HDR when the game exits.

I checked SDR 2 HDR mode and it doesn't work.

**Comment by 7gxycn08** [comment]
> > SDR 2 HDR mode will enable HDR at game start and disable HDR when the game exits.
> 
> I checked SDR 2 HDR mode and it doesn't work.

Make sure hdr is disabled when switching HDR 2 SDR to SDR 2 HDR

**Comment by buzarini** [comment]
> Make sure hdr is disabled when switching HDR 2 SDR to SDR 2 HDR

I checked several times.

Game startup:
PyAutoActions does nothing. (sdr)

Game exit:
PyAutoActions switches SDR mode to HDR mode. (sdr --> hdr)

SDR 2 HDR logic at the moment.

**Comment by 7gxycn08** [comment]
> > Make sure hdr is disabled when switching HDR 2 SDR to SDR 2 HDR
> 
> I checked several times.
> 
> Game startup: PyAutoActions does nothing. (sdr)
> 
> Game exit: PyAutoActions switches SDR mode to HDR mode. (sdr --> hdr)
> 
> SDR 2 HDR logic at the moment.
> 
> The strangest thing is that version 1.1.7 has the same behavior.

It's working normally on my side.

Lets stick to the test version for now I changed the entire logic and just added an auto switch when switching toggle modes. 

Restart your pc then test this new debug version(Console enabled by default to catch unwanted exceptions).

[PyAutoActions.test-v2.zip](https://github.com/user-attachments/files/16659820/PyAutoActions.test-v2.zip)

**Comment by 7gxycn08** [comment]
> > It's working normally on my side.
> 
> Everything works fine.
> 
> The "[Auto color management](https://support.microsoft.com/en-us/windows/auto-color-management-in-windows-11-64a4de7f-9c93-43ec-bdf1-3b12ffa0870b)" function in w11 is to blame.
> 
> Thank you very much.

Thanks for confirming.

I will add it in v1.1.8 and also some extra fixes.

**Comment by 7gxycn08** [comment]
# Feature Added In [v1.1.8](https://github.com/7gxycn08/PyAutoActions/releases/tag/v1.1.8)
