### ISSUE TITLE
HDR colour profiles

### ISSUE THREAD

**Issue by AshZaza** [7gxycn08/PyAutoActions#5]
### Discussed in https://github.com/7gxycn08/PyAutoActions/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **AshZaza** August 25, 2024</sup>
Sadly this software is ignoring  colour profiles I have created and using the "default HDR". I created colour profile with [ColourControl](https://github.com/Maassoft/ColorControl)  program (for adjusting correct black flour level). It serve me well. However PyAutoActions ignoring that profile. It just regular "light HDR" in game. If I run game without PyAutoActions it is running with my ColourControl profile. Hope this is possible to change. I tried to delete all profiles so only one is there now, no change in behavior
![Screenshot 2024-08-25 130615](https://github.com/user-attachments/assets/a8d96c72-5148-4b0f-8589-b018591cd160)
</div>

**Comment by 7gxycn08** [comment]
PyAutoActions does not change or set color profiles It must be something else that's changing your color profiles.

**Comment by AshZaza** [comment]
It looks like skipping to look at profiles values and use some "global" HDR instead. ColourControl is used only for creation of profile, not controlling (enable/disable). It is not running in background. Same thing may be done by Windows itself (Display calibration)
