### ISSUE TITLE
Primary Monitor Only Ignored

### ISSUE THREAD

**Issue by ContinuousQ** [7gxycn08/PyAutoActions#8]
My display configuration is somewhat complex, but is as follows:

Primary Monitor, Second Monitor, Third Monitor, TV.

All monitors keep HDR turned off, and the TV keeps HDR toggled on. I only want Auto Action to toggle the primary monitor for the applications I have flagged to trigger. The issue is that even with it set to "Primary Only", the other two monitors also enable HDR which forces me to alt-tab and manually toggle them back off. (This is somewhat an issue for gaming seeing as they use DDC/CI to automatically lower their brightness for gaming, which HDR ignores)

The expected behavior is that only the primary monitor will use the SDR to HDR flag and change settings when a program is launched.

NOTE: This is not a 100% of the time issue. Sometimes opening the program and completely changing the settings and then changing them back resolves this issue until the system is rebooted or Auto Actions is closed and reopened.

**Comment by 7gxycn08** [comment]
Please test this debug version if it's remembering the previous settings upon application restart.

[PyAutoActions.debug.zip](https://github.com/user-attachments/files/18265413/PyAutoActions.debug.zip)

If all went welI I will add it in the next release.

**Comment by 7gxycn08** [comment]
Fixed in [v1.2.5](https://github.com/7gxycn08/PyAutoActions/releases/tag/v1.2.5) 

I will close this issue for now feel free to open a new one anytime.

**Comment by ContinuousQ** [comment]
Settings seem to be persisting now - much appreciated. With the old Auto Actions defunct, you're my hero.

I'll let you know if I encounter any other issues - thanks mate.
